### ISSUE TITLE
update equipment info

### ISSUE THREAD

**Issue by gamermage5op** [gamermage5op/SBC-TrialsOfLoki-ProjectBoard#7]
Currently the equipment is just the defaults for the inventory system. It needs to be updated in a couple ways. 

1, the structs can contain what info we need on the weapons.  Will need to design. 
2, need to add more custom weapons, armor etc. 
3, needs to actually work. This sounds obvious but the inventory system is wack and simply editing things will require a lot of adjustment. Fuck ill probs have to do it dang

**Comment by SBCBLUNT** [comment]
updated the standard weapons to be more cool added a jank asf chest plate but ya we got this done by adding a socket to the bolverker character and then from there shrinking and rotation the assets based on each sock will def need to find a better way to do this in the futre but ya for now it works
